# baseURL = "http://localhost:1313/"
baseURL = "https://kevin-mok.gitlab.io/my-site-hugo/"
# baseURL = "/home/kevin/coding/mf-site/public"
languageCode = "en-us"
title = "Kevin Mok"
# theme = "base16"
