# baseURL: http://localhost:1313/
baseURL: https://kevin-mok.com/
# baseURL: /home/kevin/coding/mf-site/public
languageCode: en-us
# title: Kevin Mok's Website
title: Kevin Mok
# theme: base16
enableRobotsTXT: true
pygmentsUseClassic: true

params:
  author: Kevin Mok
  description: I'm a Computer Science (CS) student at the University of Toronto and an avid Linux/FOSS user. Come check out my personal site! 

menu:
  main:
  - name: resume
    url: /resume
    weight: 1
  # - name: posts/
    # url: /posts
    # weight: 6
  - name: server
    url: /server
    weight: 7
  - name: config
    url: /config
    weight: 10
  - name: card
    url: /card
    weight: 15
  # - name: letter
    # url: /letter
    # weight: 17
  # - name: credits
    # url: /credits
    # weight: 20
    
# blackfriday:
  # plainIDAnchors: true
  # hrefTargetBlank: true

disableKinds: ["RSS"]

markup:
  goldmark:
    renderer:
      unsafe: true
